POST http://localhost:8080/api/users/volunteers/new
Content-Type: application/json

{
  "name": "Shreyas Patil A",
  "email": "shreyaspatiladmin@gmail.com",
  "mobile": "1111111111",
  "talukaId": 1
}