POST http://localhost:8080/api/resources/supply
Content-Type: application/json

{
  "contactName": "shreyas",
  "mobileNumber": "7767084933",
  "address": "near market area, jalgaon",
  "resourceName": "oxygen",
  "talukaId": 1,
  "note": "Lorem Ipsum"
}